namespace: grafana

name: grafana

version: 0.0.1

readme: README.md

authors:
- Ishan Jain <ishan.jain@grafana.com>

description: Ansible collection to manage resources in Grafana

license:
- GPL-3.0-or-later

license_file: LICENSE

tags: [grafana, observability, monitoring, prometheus]

repository: https://github.com/grafana/ansible-collection

issues: https://github.com/grafana/ansible-collection/issues

build_ignore:
- .idea

