grafana_alloy_version: "1.0.0"

grafana_alloy_arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  i386: i386
  ppc64le: ppc64le

grafana_alloy_arch: "{{ arch_mapping[ansible_architecture] | default('amd64') }}"

grafana_alloy_binary_url: "https://github.com/grafana/alloy/releases/download/v{{ grafana_allot_version }}/alloy-linux-{{ grafana_alloy_arch }}.zip"

grafana_alloy_service_name: "alloy"

grafana_alloy_installation_dir: "/etc/alloy/bin"

grafana_alloy_environment_file: "service.env"

grafana_alloy_config_dir: "/etc/alloy"

grafana_alloy_config_file: "config.alloy"

grafana_alloy_service_user: "alloy"

grafana_alloy_service_group: "alloy"

grafana_alloy_working_dir: "/etc/alloy"

grafana_alloy_env_file_vars: {}

grafana_alloy_flags_extra: {}

grafana_alloy_start_after_service: ''

grafana_alloy_config: |
  prometheus.scrape "default" {
      targets = [{"__address__" = "localhost:12345"}]
      forward_to = [prometheus.remote_write.prom.receiver]
  }
  prometheus.remote_write "prom" {
    endpoint {
        url = "http://mimir:9009/api/v1/push"
    }
  }

# Configurable user groups that the Grafana Alloy can be put in so that it can access logs.
alloy_user_groups: []
